server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: Asia/Shanghai
  application:
    name: takeaway-backend
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeaway?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        session_facatory:
          statement_inspecter: com.takeaway.intercepter.JpaSqlIntercepter
  
  # Redis配置
  data:
    redis:
      database: 9
      host: 192.168.7.62
      port: 6379
      password: root
      timeout: 3000ms
      letture:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# RocketMQ配置
rocketmq:
  name-server: 192.168.7.62:9876
  producer:
    group: takeaway-producer-group
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
  consumer:
    group: takeaway-consumer-group

# 日志配置
logging:
  level:
    root: INFO
    com.takeaway: DEBUG

# springdoc配置
springdoc:
  webjars:
    # 访问前缀
    prefix:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  knife4j:
    enable: true
    production: false
    basic:
      enable: false
      username: mangrove
      password: 123456
    setting:
      swagger-model-name: 实体类列表
  default-flat-param-object: true
  packages-to-scan: com.takeaway.controller

# JWT配置
jwt:
  secret: c2VjcmV0LWtleS1mb3Itand0LXRva2VuLWp3dC1zZWNyZXQtc2lnbmluZy1rZXkK # base64编码的密钥
  expiration: 86400000 # 1天(毫秒)